### ISSUE TITLE
link the station to your station pictures

### ISSUE THREAD

**Issue by ynrng** [georgejkaye/transport-tracker#9]
[transport.georgejkaye.com/](https://transport.georgejkaye.com/)

**Comment by FrozenDude101** [comment]
Honestly not sure how George J Kaye missed this one, 0/10 unusable website

**Comment by georgejkaye** [comment]
It was on the big board, honest

**Comment by ynrng** [comment]
we will believe after we see it

**Comment by georgejkaye** [comment]
Station pictures can now be seen on the station pages
